#!/usr/bin/bash

users_files=$(find . -name "*_times" | cut -d "/" -f 2)

compare() {
	biggest=0
	while read -r user; do
		tmp=0
		while read -r user_record; do
			tmp=$(awk "BEGIN {print $tmp + $user_record}")
		done < "$user"
		echo "$user: $tmp" >> final_times
		if awk "BEGIN {exit $biggest > $tmp}"; then
			biggest=$(awk "BEGIN {print $tmp}")
		fi
	done <<< "$users_files"
	echo "$biggest"
}

compare 